Bump minimum Python version to 3.9
Due to changes with write-through `mmap`, there appeared some
issues in older versions as caught by GitHub CI:

Python 3.7, Linux, numpy 1.21
- mypy complains about passing `mmap` as `buffer` argument to `ndarray`:

ensightreader.py:645: error: Argument "buffer" to "ndarray" has incompatible type "mmap"; expected "Union[ndarray[Any, Any], bytes, bytearray, memoryview]"

Python 3.8, Linux, numpy 1.23
- `ndarray` objects created from writable `mmap` are not writable
- I could not find any relevant mentions of changes in NumPy or Python regarding this

>           assert nodes.flags.writeable
E           assert False
E            +  where False =   C_CONTIGUOUS : False\n  F_CONTIGUOUS : True\n  OWNDATA : False\n  WRITEABLE : False\n  ALIGNED : True\n  WRITEBACKIFCOPY : False\n.writeable
E            +    where   C_CONTIGUOUS : False\n  F_CONTIGUOUS : True\n  OWNDATA : False\n  WRITEABLE : False\n  ALIGNED : True\n  WRITEBACKIFCOPY : False

>                   node_array[:, 0] += translate[0]
E                   ValueError: output array is read-only